/*SELECT TOP (1000) [LOGICALREF]
      ,[ITEMCODE]
      ,[ITEMNAME]
      ,[FICHENO]
      ,[DATE_]
      ,[AMOUNT]
      ,[PRICE]
      ,[LINENETTOTAL]
      ,[LINENET]
      ,[BRANCHNR]
      ,[BRANCH]
      ,[SALESMAN]
      ,[CITY]
      ,[REGION]
      ,[LATITUDE]
      ,[LONGITUDE]
      ,[CLIENTCODE]
      ,[CLIENTNAME]
      ,[BRANDCODE]
      ,[BRAND]
      ,[CATEGORY_NAME1]
      ,[CATEGORY_NAME2]
      ,[CATEGORY_NAME3]
      ,[STARTDATE]
      ,[ENDDATE]
      ,[SPECODE]
      ,[CAPIBLOCK_CREADEDDATE]
  FROM [ETRADE].[dbo].[SALES]
  
  --- BURADA T�M SATIRLARI �EK�YORUZ--
  SELECT*FROM SALES


  -- BURADA TOPLAM SATISI SATIR SAYISINI MAX VE M�N SATISI VE ORTALAMA SATISI
  KOCAEL� SUBES� ���N �EK�YORUZ --

  SELECT SUM(LINENET) AS TOPLAMSATIS,
  COUNT(*) AS SATIRSAYISI,
  MAX(LINENET) AS MAXSATIS,MIN(LINENET) AS MINSATIS,
  AVG(LINENET) AS ORTALAMASATIS
  FROM SALES 
  WHERE BRANCH ='Kocaeli Subesi'

  --BURDA TOPLAM SATISI 50 B�NDEN FAZLA OLAN SUBELER� �EK�YORUZ--
  
SELECT BRANCH,SUM(LINENET) AS TOPLAMSATIS
FROM SALES
GROUP BY BRANCH 
HAVING SUM(LINENET) >50000
ORDER BY 2 DESC

-- BURADA ANKARA SUBES�NDE BEL�RL� B�R TAR�HTEK� SATISI �EK�YORUZ--

SELECT BRANCH AS SUBE,DATE_ AS TARIH, SUM(LINENET) AS TOPLAMSATIS,COUNT(*) SATIRSAYISI
FROM SALES
WHERE BRANCH='ANKARA Subesi' --AND DATE_='2017-01-05'
GROUP BY BRANCH,DATE_
ORDER BY DATE_

SELECT BRANCH AS SUBE,DATE_ AS TARIH, SUM(LINENET) AS TOPLAMSATIS,COUNT(*) SATIRSAYISI
FROM SALES
GROUP BY BRANCH,DATE_
ORDER BY BRANCH,DATE_

SELECT DATE_ ,BRANCH,SUM(LINENET) FROM SALES
GROUP BY DATE_,BRANCH 
RDER BY DATE_ SUM(LINENET) DESC;*/

SELECT CATEGORY_NAME1,BRAND,CATEGORY_NAME2,SUM(LINENET),CATEGORY_NAME3 FROM SALES
WHERE CATEGORY_NAME1 IS NOT NULL AND CATEGORY_NAME2 IS NOT NULL AND CATEGORY_NAME3 IS NOT NULL AND CATEGORY_NAME1='GIDA'
GROUP BY CATEGORY_NAME1,CATEGORY_NAME2,CATEGORY_NAME3,BRAND
ORDER BY SUM(LINENET) DESC  